import type { Product } from '@/types';

export const STATIC_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Merino Wool Turtleneck',
    shortDescription: 'Ultra-soft Italian merino, timeless silhouette.',
    fullDescription: 'Crafted from 100% Italian merino wool, this premium turtleneck sweater features a relaxed fit with dropped shoulders and ribbed cuffs. Perfect for layering or wearing solo, it delivers warmth without bulk.',
    price: 189,
    category: 'clothing',
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80',
    tags: ['wool', 'knitwear', 'winter'],
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Classic Leather Watch',
    shortDescription: 'Minimalist design meets Swiss precision.',
    fullDescription: 'This meticulously crafted timepiece features a sapphire crystal glass, genuine Italian leather strap, and Japanese quartz movement. Water-resistant to 50m.',
    price: 295,
    category: 'accessories',
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf31?w=600&q=80',
    tags: ['watch', 'leather', 'minimalist'],
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: '3',
    title: 'Ceramic Table Lamp',
    shortDescription: 'Handcrafted artisan piece for ambient glow.',
    fullDescription: 'Each lamp is individually hand-thrown by skilled artisans. Features a natural clay glaze that diffuses light beautifully. Includes dimmable LED bulb.',
    price: 145,
    category: 'home',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80',
    tags: ['lamp', 'ceramic', 'handmade'],
    createdAt: '2025-01-25T10:00:00Z',
  },
  {
    id: '4',
    title: 'Wireless Earbuds Pro',
    shortDescription: 'Immersive sound with active noise cancellation.',
    fullDescription: 'Premium audio with 40mm custom drivers. Features adaptive ANC, transparency mode, and 30-hour battery life. Ergonomic fit for all-day comfort.',
    price: 349,
    category: 'electronics',
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80',
    tags: ['audio', 'wireless', 'premium'],
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: '5',
    title: 'Luxury Face Serum',
    shortDescription: 'Vitamin C-infused radiance booster.',
    fullDescription: 'A powerful blend of 15% vitamin C, ferulic acid, and hyaluronic acid. Clinically proven to reduce fine lines and improve skin brightness in 4 weeks.',
    price: 89,
    category: 'beauty',
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab3be?w=600&q=80',
    tags: ['skincare', 'serum', 'anti-aging'],
    createdAt: '2025-02-05T10:00:00Z',
  },
  {
    id: '6',
    title: 'Linen Summer Blazer',
    shortDescription: 'Breathable elegance for warm days.',
    fullDescription: 'Made from premium Belgian linen with a modern unstructured design. Features a soft shoulder, patch pockets, and horn buttons. Fully lined with cotton.',
    price: 325,
    category: 'clothing',
    rating: 4.4,
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4b7f?w=600&q=80',
    tags: ['linen', 'blazer', 'summer'],
    createdAt: '2025-02-10T10:00:00Z',
  },
  {
    id: '7',
    title: 'Titanium Sunglasses',
    shortDescription: 'Ultra-lightweight frame with UV400 protection.',
    fullDescription: 'Aerospace-grade titanium frame weighing only 12g. Polarized lenses with anti-scratch coating. Includes premium leather case.',
    price: 275,
    category: 'accessories',
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80',
    tags: ['sunglasses', 'titanium', 'polarized'],
    createdAt: '2025-02-15T10:00:00Z',
  },
  {
    id: '8',
    title: 'Velvet Accent Chair',
    shortDescription: 'Mid-century modern comfort.',
    fullDescription: 'Luxurious velvet upholstery with solid oak legs. Deep cushioning provides exceptional comfort. Available in three rich colors.',
    price: 450,
    category: 'home',
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
    tags: ['chair', 'velvet', 'modern'],
    createdAt: '2025-02-20T10:00:00Z',
  },
  {
    id: '9',
    title: 'Smart Home Speaker',
    shortDescription: 'Premium sound with voice control.',
    fullDescription: '360° spatial audio with automatic room calibration. Works with all major voice assistants. Premium wool speaker grille.',
    price: 199,
    category: 'electronics',
    rating: 4.3,
    imageUrl: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?w=600&q=80',
    tags: ['speaker', 'smart home', 'audio'],
    createdAt: '2025-02-25T10:00:00Z',
  },
  {
    id: '10',
    title: 'Rose Gold Perfume',
    shortDescription: 'Intoxicating floral notes.',
    fullDescription: 'A mesmerizing blend of Turkish rose, peony, and soft musk. Long-lasting sillage. Hand-poured in Grasse, France.',
    price: 165,
    category: 'beauty',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683b33f?w=600&q=80',
    tags: ['perfume', 'floral', 'luxury'],
    createdAt: '2025-03-01T10:00:00Z',
  },
  {
    id: '11',
    title: 'Cashmere Scarf',
    shortDescription: 'Pure Mongolian cashmere luxury.',
    fullDescription: 'Hand-knitted from the finest Mongolian cashmere. Exceptionally soft and warm. Generous dimensions for versatile styling.',
    price: 245,
    category: 'accessories',
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80',
    tags: ['scarf', 'cashmere', 'winter'],
    createdAt: '2025-03-05T10:00:00Z',
  },
  {
    id: '12',
    title: 'Minimalist Desk Set',
    shortDescription: 'Japanese-inspired workspace organization.',
    fullDescription: 'Complete desk organizer in brushed aluminum. Includes pen holder, paper tray, and device stand. Clean aesthetic for focused work.',
    price: 89,
    category: 'home',
    rating: 4.4,
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&q=80',
    tags: ['desk', 'organization', 'minimalist'],
    createdAt: '2025-03-10T10:00:00Z',
  },
];